-- MySQL Script generated by MySQL Workbench
-- Sun Dec 18 00:43:38 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema saboteur
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `saboteur`.`USERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `USERS` (
  `idUSERS` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'ID del usuario para su busqueda rapida',
  `NICKNAME` VARCHAR(20) NOT NULL,
  `FULL NAME` VARCHAR(45) NOT NULL,
  `PASSWORD` VARCHAR(8) NOT NULL,
  `DATE` DATE NOT NULL,
  `SEX` VARCHAR(1) NOT NULL,
  `PHOTO` LONGBLOB NULL,
  PRIMARY KEY (`idUSERS`),
  UNIQUE INDEX `ID_UNIQUE` (`idUSERS` ASC),
  UNIQUE INDEX `Nick_UNIQUE` (`NICKNAME` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `saboteur`.`GAMES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `saboteur`.`GAMES` (
  `idGAMES` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(20) NOT NULL,
  `STATUS` INT UNSIGNED NOT NULL DEFAULT 0,
  `HOST` INT UNSIGNED NOT NULL,
  `PLAYER_NUM` INT UNSIGNED NOT NULL DEFAULT 0,
  `MAX_NUM` INT UNSIGNED NOT NULL,
  `TURN` INT UNSIGNED NOT NULL DEFAULT 0,
  `WINNER` VARCHAR(30) NULL,
  `TURN_NM` INT UNSIGNED NOT NULL,
  `DATE` VARCHAR(10) NOT NULL,
  `TURN_NEXT` INT(2) UNSIGNED NULL DEFAULT '1',
  PRIMARY KEY (`idGAMES`),
  UNIQUE INDEX `ID_UNIQUE` (`idGAMES` ASC),
  UNIQUE INDEX `Nombre_UNIQUE` (`NAME` ASC),
  CONSTRAINT `ID_Creador`
    FOREIGN KEY (`HOST`)
    REFERENCES `saboteur`.`USERS` (`idUSERS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `saboteur`.`GAMES_USERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GAMES_USERS` (
  `idGAME` INT UNSIGNED NOT NULL,
  `idUSERS` INT UNSIGNED NOT NULL,
  `PLAYERTYPE` VARCHAR(1) NULL,
  `TURN` INT(2) UNSIGNED NULL,
  PRIMARY KEY (`idGAME`, `idUSERS`),
  INDEX `ID` (`idUSERS` ASC),
  CONSTRAINT `ID_partida`
    FOREIGN KEY (`idGAME`)
    REFERENCES `saboteur`.`GAMES` (`idGAMES`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ID_usuario`
    FOREIGN KEY (`idUSERS`)
    REFERENCES `saboteur`.`USERS` (`idUSERS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `saboteur`.`USER_CARDS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `USER_CARDS` (
  `idCARD` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `POS_CARD` INT(2) UNSIGNED NOT NULL,
  `CARD_TYPE` INT(2) UNSIGNED NOT NULL,
  `USERS_idUSERS` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idCARD`),
  INDEX `fk_CARDS_USERS1_idx` (`USERS_idUSERS` ASC),
  CONSTRAINT `fk_CARDS_USERS1`
    FOREIGN KEY (`USERS_idUSERS`)
    REFERENCES `saboteur`.`USERS` (`idUSERS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `saboteur`.`GAME_CARDS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GAME_CARDS` (
  `idGAME` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idCARD` INT NOT NULL,
  `CARD_XPOS` INT(2) NULL,
  `CARD_YPOS` INT(2) NULL,
  `CARD_TYPE` INT(2) NULL,
  INDEX `fk_GAME_CARDS_GAMES1_idx` (`idGAME` ASC),
  PRIMARY KEY (`idCARD`),
  CONSTRAINT `fk_GAME_CARDS_GAMES1`
    FOREIGN KEY (`idGAME`)
    REFERENCES `saboteur`.`GAMES` (`idGAMES`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
